image: nixos/latest
sources:
- https://git.sr.ht/~mcf/cproc
- git://c9x.me/qbe.git
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
packages:
- nixpkgs.gcc
- nixpkgs.gnumake
tasks:
- build: |
    PATH=$HOME/qbe:$PATH
    make -C qbe CC=cc
    cd cproc
    ./configure --with-ldso=
    make all check bootstrap
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
