image: openbsd/latest
sources:
- https://git.sr.ht/~mcf/cproc
- git://c9x.me/qbe.git
tasks:
- setup: |
    # avoid __asm__ on non __GNUC__ compilers
    doas patch -d /usr/include < cproc/.builds/openbsd.diff
- build: |
    PATH=$HOME/qbe:$PATH
    make -C qbe
    cd cproc
    ./configure
    make all check bootstrap
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc-builds@lists.sr.ht>"
